module.exports = {
  categories: {
    popularWithWomen: '/popularwithwomen',
    verifiedAmateurs: '/video?c=138',
    verifiedModels: '/video?c=139',
    virtualReality: '/vr',
    '60Fps': '/video?c=105',
    amateur: '/video?c=3',
    anal: '/video?c=35',
    arab: '/video?c=98',
    asian: '/video?c=1',
    babe: '/categories/babe',
    babysitter: '/video?c=89',
    bbw: '/video?c=6',
    behindTheScenes: '/video?c=141',
    bigAss: '/video?c=4',
    bigDick: '/video?c=7',
    bigTits: '/video?c=8',
    bisexualMale: '/video?c=76',
    blonde: '/video?c=9',
    blowjob: '/video?c=13',
    bondage: '/video?c=10',
    brazilian: '/video?c=102',
    british: '/video?c=96',
    brunette: '/video?c=11',
    bukkake: '/video?c=14',
    cartoon: '/video?c=86',
    casting: '/video?c=90',
    celebrity: '/video?c=12',
    closedCaptions: '/video?c=732',
    college: '/categories/college',
    compilation: '/video?c=57',
    cosplay: '/video?c=241',
    creampie: '/video?c=15',
    cuckold: '/video?c=242',
    cumshot: '/video?c=16',
    czech: '/video?c=100',
    describedVideo: '/described-video',
    doublePenetration: '/video?c=72',
    ebony: '/video?c=17',
    euro: '/video?c=55',
    exclusive: '/video?c=115',
    feet: '/video?c=93',
    femaleOrgasm: '/video?c=502',
    fetish: '/video?c=18',
    fingering: '/video?c=592',
    fisting: '/video?c=19',
    french: '/video?c=94',
    funny: '/video?c=32',
    gangbang: '/video?c=80',
    gay: '/gayporn',
    german: '/video?c=95',
    handjob: '/video?c=20',
    hardcore: '/video?c=21',
    hdPorn: '/hd',
    hentai: '/categories/hentai',
    indian: '/video?c=101',
    interactive: '/interactive',
    interracial: '/video?c=25',
    italian: '/video?c=97',
    japanese: '/video?c=111',
    korean: '/video?c=103',
    latina: '/video?c=26',
    lesbian: '/video?c=27',
    massage: '/video?c=78',
    masturbation: '/video?c=22',
    mature: '/video?c=28',
    milf: '/video?c=29',
    muscularMen: '/video?c=512',
    music: '/video?c=121',
    oldYoung: '/video?c=181',
    orgy: '/video?c=2',
    parody: '/video?c=201',
    party: '/video?c=53',
    pissing: '/video?c=211',
    pornstar: '/categories/pornstar',
    pov: '/video?c=41',
    public: '/video?c=24',
    pussyLicking: '/video?c=131',
    reality: '/video?c=31',
    redHead: '/video?c=42',
    rolePlay: '/video?c=81',
    romantic: '/video?c=522',
    roughSex: '/video?c=67',
    russian: '/video?c=99',
    school: '/video?c=88',
    sfw: '/sfw',
    smallTits: '/video?c=59',
    smoking: '/video?c=91',
    soloFemale: '/video?c=492',
    soloMale: '/video?c=92',
    squirt: '/video?c=69',
    stepFantasy: '/video?c=444',
    strapOn: '/video?c=542',
    striptease: '/video?c=33',
    tattooedWomen: '/video?c=562',
    teen18: '/categories/teen',
    threesome: '/video?c=65',
    toys: '/video?c=23',
    transgender: '/transgender',
    verifiedCouples: '/video?c=482',
    vintage: '/video?c=43',
    webcam: '/video?c=61',
  },
  rankings: {
    mostViewed: 'mv',
    topRated: 'tr',
    hottest: 'ht',
    longest: 'lg',
    newest: 'cm',
  },
  ranges: {
    daily: 't',
    weekly: 'w',
    monthly: 'm',
    yearly: 'y',
    allTime: 'a',
  },
  production: {
    homemade: 'homemade',
    professional: 'professional',
  },
  quality: {
    fourK: '4',
    fourteenFourtyK: '3',
    tenEighty: '2',
  },
  video: {
    all: '',
    premiumOnly: 'premium',
    downloadOnly: 'download',
  },
  params: {
    rankings: 'o',
    quality: 'hd',
    production: 'p',
    ranges: 't',
  },
  options: [
    'rankings',
    'quality',
    'production',
    'ranges',
    'premiumOnly',
    'downloadOnly',
  ],
};
